const genres = [
    "Action",
    "Adventure",
    "Animation",
    "Biography",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Family",
    "Fantasy",
    "Fiction",
    "Film-Noir",
    "Game Show",
    "History",
    "Horror",
    "Music",
    "Musical",
    "Mystery",
    "News",
    "Reality TV",
    "Romance",
    "Romance",
    "Sci-fi",
    "Superhero",
    "Sport",
    "Talk-show",
    "Thriller",
    "War",
    "Western",
]

module.exports = genres